### ISSUE TITLE
Page load fails if autocomplete disabled

### ISSUE THREAD

**Issue by dgw** [thelounge/lounge#1647]
After updating from 2.4.0 to 2.5.0 on my production instance, the app simply failed to load after login, stalling on "Loading the app". The JS console showed me a nice error trace:

````
Uncaught TypeError: $(...).textcomplete is not a function
    at HTMLInputElement.<anonymous> (options.js:121)
    at HTMLDivElement.dispatch (jquery.js:5206)
    at HTMLDivElement.elemData.handle (jquery.js:5014)
    at Object.trigger (jquery.js:8201)
    at HTMLInputElement.<anonymous> (jquery.js:8269)
    at Function.each (jquery.js:362)
    at jQuery.fn.init.each (jquery.js:157)
    at jQuery.fn.init.trigger (jquery.js:8268)
    at Object.<anonymous> (options.js:125)
    at __webpack_require__ (bootstrap c22410d6bdbfb4c08f65:54)
````

_(I pulled the above trace later, from my local debug instance checked out at tag `v2.5.0`. The same bug manifests on current `master`.)_

Once I found the error in the console, I kind of just jumped on a hunch and tried clearing LocalStorage/cookies, then reloading—the app connected fine. I put all my settings back the way they had been—failure. So I cleared again and started reloading the app after every setting change.

It failed to load right after I unchecked "Enable autocomplete". Conclusion: The Lounge v2.5.0 cannot be run without autocomplete enabled on the client. I'm guessing not many of the active contributors have autocomplete turned off, or this would have been caught during testing of whatever PR broke it. (Even though I worked on several PRs during the incubation of 2.5.0, I never bothered turning off autocomplete on my debug instance… If I had, I probably would have caught this _before_ release. :disappointed:) It seems there's no test coverage of the setting, either. (I can't find any test coverage of the client at all, actually, not that I'm super familiar with the tests file layout.)

The code referenced in `options.js:121` hasn't been touched in 4 months (it was the same in 2.4.0 stable), so I thought something must have changed elsewhere. If I'm lucky, I'll come up with a PR later this week, because a full course of `git bisect` pointed me to 1e2d35f—a starting point for fixing the regression. (Not tonight, because I already stayed up longer than I should have just writing this bug report! :laughing:)

**Comment by MaxLeiter** [comment]
Here's a temporary fix. Just paste into developer tools console
```
var x = JSON.parse(localStorage.settings);
x.autocomplete = true;
localStorage.settings = JSON.stringify(x);
```

**Comment by MaxLeiter** [comment]
To fix this you'll just need to add `require("jquery-textcomplete");` to top of `options.js`

**Comment by starquake** [comment]
This also prevents it from working on my phone

**Comment by Komic** [comment]
Oh so that's why my instance exploded the other day. At least there's a temporary fix, thanks!
